const API='https://kvfjjtkwxxbvzlicwnrz.supabase.co/functions/v1/vtal-api';
const STATUSES={ready:'Atendemos 100%',partial:'Atendemos em parte',no:'Não atendemos',question:'Dúvidas',attention:'Ponto de Atenção'};
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token='',D={groups:[],items:[],permissions:{}},editing=null;
function getToken(){try{if(parent&&parent!==window&&parent.__PORTAL_TOKEN__)return parent.__PORTAL_TOKEN__}catch{}try{if(opener&&opener.__PORTAL_TOKEN__)return opener.__PORTAL_TOKEN__}catch{}return sessionStorage.getItem('portal_vtal_token')||''}
function requestToken(){return new Promise(resolve=>{if(!('BroadcastChannel'in window))return resolve('');const channel=new BroadcastChannel('livion-portal-session'),requestId=crypto.randomUUID(),timer=setTimeout(()=>{channel.close();resolve('')},1800);channel.onmessage=e=>{if(e.data?.type==='PORTAL_TOKEN_RESPONSE'&&e.data?.requestId===requestId){clearTimeout(timer);channel.close();resolve(e.data.token||'')}};channel.postMessage({type:'PORTAL_TOKEN_REQUEST',requestId})})}
function openThroughPortal(){const url=new URL('./',location.href);url.searchParams.set('app','vtal');location.replace(url.href)}
async function renew(force=false){try{if(parent&&parent!==window&&parent.__PORTAL_GET_TOKEN__)return await parent.__PORTAL_GET_TOKEN__(force)}catch{}try{if(opener&&opener.__PORTAL_GET_TOKEN__)return await opener.__PORTAL_GET_TOKEN__(force)}catch{}return await requestToken()||getToken()}
async function api(path,opt={}){const send=t=>fetch(API+path,{...opt,headers:{authorization:'Bearer '+t,'content-type':'application/json',...(opt.headers||{})},cache:'no-store'});token=await renew(false)||token;if(!token){openThroughPortal();throw Error('Abrindo pelo Portal Livion…')}sessionStorage.setItem('portal_vtal_token',token);let r=await send(token);if(r.status===401){token=await renew(true)||token;r=await send(token)}const body=await r.json().catch(()=>({}));if(!r.ok)throw Error(({FORBIDDEN:'Seu usuário não tem permissão para esta ação.',CONFLICT:'O checklist foi alterado por outra pessoa. Atualize e tente novamente.',INVALID_ITEM:'Revise os campos do requisito.'})[body.error]||body.error||'Falha ao acessar o checklist.');return body}
const normalized=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function filtered(){const q=normalized($('search').value),group=$('groupFilter').value,status=$('statusFilter').value,archived=$('archivedFilter').checked;return D.items.filter(i=>i.archived===archived&&(!group||i.group===group)&&(!status||(status==='unrated'?i.status===null:i.status===status))&&(!q||normalized(`${i.id} ${i.text} ${i.notes} ${i.owner}`).includes(q))).sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id,'pt-BR',{numeric:true}))}
function counts(){const result={total:0,unrated:0,ready:0,partial:0,no:0,question:0,attention:0};for(const i of D.items.filter(x=>!x.archived)){result.total++;result[i.status??'unrated']++}return result}
function render(){const c=counts(),metrics=[['total','Total',c.total],['unrated','Não avaliados',c.unrated],['ready',STATUSES.ready,c.ready],['partial',STATUSES.partial,c.partial],['no',STATUSES.no,c.no],['attention','Pontos de atenção',c.attention]];$('metrics').innerHTML=metrics.map(([key,label,value])=>`<button class="metric ${key}" data-metric="${key}"><span>${label}</span><b>${value}</b></button>`).join('');document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>{$('archivedFilter').checked=false;$('statusFilter').value=b.dataset.metric==='total'?'':b.dataset.metric;renderList()});$('newBtn').classList.toggle('hidden',!D.permissions.edit);$('exportBtn').disabled=!D.permissions.export;renderList()}
function renderList(){const rows=filtered();$('resultCount').textContent=`${rows.length} requisito(s)`;$('updatedAt').textContent=D.updated_at?`Última alteração: ${new Date(D.updated_at).toLocaleString('pt-BR')} · ${D.updated_by||''}`:'Base inicial ainda sem alterações';$('list').innerHTML=rows.map(i=>{const group=D.groups.find(g=>g.id===i.group);return `<article class="requirement ${i.archived?'archived':''}"><div class="req-id">${esc(i.id)}</div><div class="req-text"><b>${esc(i.text)}</b><small>${esc(group?.title||i.group)}${i.notes?' · '+esc(i.notes):''}</small></div><div class="status-cell"><span class="pill ${i.status||''}">${i.status?STATUSES[i.status]:'Ainda não avaliado'}</span><span class="owner">${esc(i.owner||'Sem responsável')}</span></div><button class="btn" data-edit="${esc(i.id)}" ${D.permissions.edit?'':'disabled'}>Editar</button></article>`}).join('')||'<div class="empty">Nenhum requisito encontrado com os filtros atuais.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(D.items.find(i=>i.id===b.dataset.edit)))}
function populateFilters(){const groups='<option value="">Todas</option>'+D.groups.map(g=>`<option value="${esc(g.id)}">${esc(g.title)}</option>`).join('');$('groupFilter').innerHTML=groups;$('editGroup').innerHTML=D.groups.map(g=>`<option value="${esc(g.id)}">${esc(g.title)}</option>`).join('');const statuses='<option value="">Todas</option><option value="unrated">Ainda não avaliado</option>'+Object.entries(STATUSES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');$('statusFilter').innerHTML=statuses;$('editStatus').innerHTML='<option value="">Ainda não avaliado</option>'+Object.entries(STATUSES).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}
function openEditor(item=null){editing=item||null;$('editorTitle').textContent=item?'Editar requisito':'Novo requisito';$('editGroup').value=item?.group||D.groups[0]?.id||'';$('editText').value=item?.text||'';$('editStatus').value=item?.status||'';$('editOwner').value=item?.owner||'';$('editNotes').value=item?.notes||'';$('editArchived').checked=Boolean(item?.archived);$('editor').showModal()}
async function save(e){e.preventDefault();if(!D.permissions.edit)return;const item={id:editing?.id||`NOVO-${crypto.randomUUID().slice(0,8).toUpperCase()}`,group:$('editGroup').value,text:$('editText').value.trim(),notes:$('editNotes').value.trim(),owner:$('editOwner').value.trim(),status:$('editStatus').value||null,order:editing?.order??Math.max(0,...D.items.map(i=>i.order))+1,archived:$('editArchived').checked};const btn=$('saveBtn');btn.disabled=true;try{D=await api('/item',{method:'POST',body:JSON.stringify({revision:D.revision,item})});$('editor').close();populateFilters();render();flash('Requisito salvo.')}catch(err){alert(err.message);if(err.message.includes('outra pessoa'))await reload()}finally{btn.disabled=false}}
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`}
async function exportCsv(){if(!D.permissions.export)return;await api('/export');const rows=filtered(),head=['ID','Categoria','Requisito','Classificação','Responsável','Observações','Arquivado'];const csv='\ufeff'+[head,...rows.map(i=>[i.id,D.groups.find(g=>g.id===i.group)?.title||i.group,i.text,i.status?STATUSES[i.status]:'Ainda não avaliado',i.owner,i.notes,i.archived?'Sim':'Não'])].map(r=>r.map(csvCell).join(';')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`checklist-vtal-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
function flash(message){$('flash').textContent=message;$('flash').classList.remove('hidden');setTimeout(()=>$('flash').classList.add('hidden'),3000)}
async function reload(){D=await api('/bootstrap');populateFilters();$('loading').classList.add('hidden');$('app').classList.remove('hidden');render()}
for(const id of ['search','groupFilter','statusFilter','archivedFilter'])$(id).addEventListener(id==='search'?'input':'change',renderList);$('editorForm').addEventListener('submit',save);$('closeEditor').onclick=$('cancelEditor').onclick=()=>$('editor').close();$('newBtn').onclick=()=>openEditor();$('reloadBtn').onclick=()=>reload().catch(e=>alert(e.message));$('exportBtn').onclick=()=>exportCsv().catch(e=>alert(e.message));reload().catch(e=>{$('loading').innerHTML=`<b>Não foi possível abrir o checklist.</b><br>${esc(e.message)}<br><button class="btn" onclick="location.reload()">Tentar novamente</button>`});
