import { createClient } from 'jsr:@supabase/supabase-js@2';
const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const TENANT='911e1aee-070e-421b-ae71-439f01c2263e', CLIENT='88cf5cba-9f67-467d-8a51-9638200bed52';
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
function decJwt(t:string){try{return JSON.parse(atob(t.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return {}}}
async function auth(req:Request){const t=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,''); if(!t) throw new Error('UNAUTHORIZED'); const p=decJwt(t); if(p.tid!==TENANT) throw new Error('UNAUTHORIZED'); const aud=String(p.aud||''); if(aud!==CLIENT && aud!==`api://${CLIENT}` && !aud.includes(CLIENT)) { /* Graph access tokens can use a Graph audience; validate through Graph below */ }
 const gr=await fetch('https://graph.microsoft.com/v1.0/me?$select=id,displayName,mail,userPrincipalName',{headers:{authorization:`Bearer ${t}`}}); if(!gr.ok) throw new Error('UNAUTHORIZED'); const me=await gr.json(); const email=String(me.mail||me.userPrincipalName||'').toLowerCase();
 let q=await db.from('portal_users').select('*').eq('microsoft_id',me.id).maybeSingle(); if(!q.data) q=await db.from('portal_users').select('*').ilike('email',email).maybeSingle(); const u=q.data; if(!u?.active) throw new Error('FORBIDDEN'); const apps=Array.isArray(u.apps)?u.apps:[]; const admin=u.profile==='ADMINISTRADOR'; if(!admin&&!apps.includes('estoque')) throw new Error('FORBIDDEN'); return {u,email,admin,actions:Array.isArray(u.actions)?u.actions:[],me}; }
const can=(a:any,k:string)=>a.admin||a.actions.includes(k);
async function audit(a:any,action:string,target:string,detail:any={}){await db.from('access_audit').insert({actor_email:a.email,action,target,detail});}
async function stockRows(){const {data,error}=await db.from('inventory_stock_current').select('*').order('description').limit(2000); if(error)throw error; return data||[]}
async function dashboard(){const {data,error}=await db.from('inventory_dashboard').select('*').single(); if(error)throw error; return data}
async function bootstrap(a:any){const [dash,stock,recent,reqs,sups,monthly,cons]=await Promise.all([
 dashboard(), stockRows(),
 db.from('inventory_movements').select('movement_id,occurred_at,movement_type,product_id,quantity,total_value,unit_value,requester_id,supplier_id,document_number,notes,user_email,source,from_location,to_location,purpose').order('occurred_at',{ascending:false}).limit(300),
 db.from('inventory_requesters').select('*').order('name').limit(1000), db.from('inventory_suppliers').select('*').order('name').limit(1000),
 db.from('inventory_accounting_monthly').select('*').limit(24), db.from('inventory_consumption_30d').select('*').order('out_30d',{ascending:false}).limit(20)
 ]); return {dashboard:dash,stock,recent:recent.data||[],requesters:reqs.data||[],suppliers:sups.data||[],monthly:monthly.data||[],consumption:cons.data||[],user:{name:a.u.name,email:a.email,profile:a.u.profile,administrator:a.admin,actions:a.actions},permissions:{viewValues:can(a,'estoque.visualizar_valores'),entry:can(a,'estoque.movimentar_entrada'),exit:can(a,'estoque.movimentar_saida'),adjust:can(a,'estoque.ajustar'),transfer:can(a,'estoque.transferir'),product:can(a,'estoque.cadastrar_produto')||can(a,'estoque.editar_produto'),supplier:can(a,'estoque.gerenciar_fornecedores'),requester:can(a,'estoque.gerenciar_solicitantes'),export:can(a,'estoque.exportar'),history:can(a,'estoque.visualizar_historico')}}}
async function createMovement(a:any,b:any){const type=String(b.movement_type||'').toUpperCase(); const pm:any={ENTRADA:'estoque.movimentar_entrada',SAIDA:'estoque.movimentar_saida',AJUSTE_POSITIVO:'estoque.ajustar',AJUSTE_NEGATIVO:'estoque.ajustar',TRANSFERENCIA:'estoque.transferir'}; if(!pm[type]||!can(a,pm[type])) throw new Error('FORBIDDEN'); const qty=Number(b.quantity); if(!b.product_id||!Number.isFinite(qty)||qty<=0)throw new Error('INVALID_MOVEMENT');
 if(type==='SAIDA'||type==='AJUSTE_NEGATIVO'){const {data}=await db.from('inventory_stock_current').select('balance').eq('product_id',b.product_id).maybeSingle(); if(!a.admin && Number(data?.balance||0)<qty)throw new Error('INSUFFICIENT_STOCK');}
 const id=crypto.randomUUID(); const row={movement_id:id,occurred_at:b.occurred_at||new Date().toISOString(),movement_type:type,product_id:b.product_id,quantity:qty,total_value:type==='ENTRADA'&&b.total_value!=null?Number(b.total_value):null,unit_value:type==='ENTRADA'&&b.unit_value!=null?Number(b.unit_value):null,requester_id:b.requester_id||null,supplier_id:b.supplier_id||null,document_number:b.document_number||null,notes:b.notes||null,user_email:a.email,source:'PORTAL',from_location:b.from_location||null,to_location:b.to_location||null,purpose:type==='SAIDA'?(b.purpose||'CONSUMO_INTERNO'):(b.purpose||null)}; const {error}=await db.from('inventory_movements').insert(row); if(error)throw error; await audit(a,'INVENTORY_'+type,b.product_id,{quantity:qty,document_number:row.document_number}); return {ok:true,id};}
function photo(v:any){const value=String(v||'').trim();if(!value)return null;if(value.length>1500000||(!value.startsWith('data:image/')&&!value.startsWith('https://')))throw new Error('INVALID_PHOTO');return value}
async function upsertProduct(a:any,b:any){if(!can(a,b.product_id?'estoque.editar_produto':'estoque.cadastrar_produto'))throw new Error('FORBIDDEN'); const pid=b.product_id||('PROD-'+crypto.randomUUID().slice(0,8).toUpperCase()); const row={product_id:pid,pn:String(b.pn||'').trim(),description:String(b.description||b.pn||'').trim(),category:b.category||null,item_type:b.item_type||null,unit:b.unit||'UNIDADE',min_stock:b.min_stock===''||b.min_stock==null?null:Number(b.min_stock),ideal_stock:b.ideal_stock===''||b.ideal_stock==null?null:Number(b.ideal_stock),usage_notes:b.usage_notes||null,default_location:b.default_location||null,photo_url:photo(b.photo_url),photo_url_2:photo(b.photo_url_2),photo_url_3:photo(b.photo_url_3),photo_url_4:photo(b.photo_url_4),status:b.status||'ATIVO',notes:b.notes||null,updated_at:new Date().toISOString(),created_by:a.email}; if(!row.pn||!row.description)throw new Error('INVALID_PRODUCT'); const {error}=await db.from('inventory_products').upsert(row,{onConflict:'product_id'});if(error)throw error;await audit(a,'INVENTORY_PRODUCT_UPSERT',pid,{pn:row.pn});return {ok:true,product_id:pid}}
async function upsertPerson(a:any,b:any,kind:'requester'|'supplier'){const perm=kind==='requester'?'estoque.gerenciar_solicitantes':'estoque.gerenciar_fornecedores';if(!can(a,perm))throw new Error('FORBIDDEN');const table=kind==='requester'?'inventory_requesters':'inventory_suppliers';const idKey=kind==='requester'?'requester_id':'supplier_id';const id=b[idKey]||crypto.randomUUID();const row:any={[idKey]:id,name:String(b.name||'').trim(),document:b.document||null,phone:b.phone||null,email:b.email||null,photo_url:photo(b.photo_url),photo_url_2:photo(b.photo_url_2),photo_url_3:photo(b.photo_url_3),photo_url_4:photo(b.photo_url_4),status:b.status||'ATIVO',notes:b.notes||null,updated_at:new Date().toISOString()};if(kind==='requester')row.department=b.department||null;else row.address=b.address||null;if(!row.name)throw new Error('INVALID_NAME');const {error}=await db.from(table).upsert(row,{onConflict:idKey});if(error)throw error;await audit(a,'INVENTORY_'+kind.toUpperCase()+'_UPSERT',id,{name:row.name});return {ok:true,id}}
async function report(a:any,u:URL){if(!can(a,'estoque.exportar')&&!a.admin)throw new Error('FORBIDDEN');const from=u.searchParams.get('from'),to=u.searchParams.get('to');let q=db.from('inventory_movements').select('*').order('occurred_at');if(from)q=q.gte('occurred_at',from+'T00:00:00');if(to)q=q.lte('occurred_at',to+'T23:59:59.999');const [mv,pos]=await Promise.all([q.limit(10000),db.from('inventory_accounting_position').select('*').limit(3000)]);return {movements:mv.data||[],position:pos.data||[],from,to}}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('',{headers:cors});try{const a=await auth(req),u=new URL(req.url),p=u.pathname.split('/').pop()||'';if(req.method==='GET'&&p==='health')return json({ok:true,version:1});if(req.method==='GET'&&p==='bootstrap')return json(await bootstrap(a));if(req.method==='GET'&&p==='report')return json(await report(a,u));if(req.method==='POST'&&p==='movement')return json(await createMovement(a,await req.json()));if(req.method==='POST'&&p==='product')return json(await upsertProduct(a,await req.json()));if(req.method==='POST'&&p==='requester')return json(await upsertPerson(a,await req.json(),'requester'));if(req.method==='POST'&&p==='supplier')return json(await upsertPerson(a,await req.json(),'supplier'));return json({error:'NOT_FOUND'},404)}catch(e){const m=String(e?.message||e);const status=m.includes('UNAUTHORIZED')?401:m.includes('FORBIDDEN')?403:m.includes('INSUFFICIENT')||m.includes('INVALID_')?400:500;return json({error:m},status)}});
