import {volumeChart,repairChart,comparisonChart} from './charts.mjs';
import {CLIENTS, STATUSES, VERSION, statistics, groupStats, presentationRows, percent, money, comparisonCSV} from './domain.mjs';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#148774','#d36365','#286dde','#e8ae49','#8d86ae'];
const demo=new URLSearchParams(location.search).get('demo')==='1' && ['127.0.0.1','localhost'].includes(location.hostname);
const endpoint='https://kvfjjtkwxxbvzlicwnrz.supabase.co/functions/v1/desempenho-api';
const state={rows:[],allowed:[],clients:[],measurement:'',pn:'',filterStatus:'',filterWarranty:'',filterTester:'',search:'',team:new Set(),compare:new Set(),tab:'overview',sort:'real',statusA:'REPARADO',statusB:'IRREPARÁVEL',present:false,selected:'',updated:'',loading:false,error:'',canManage:false,access:null,demoProfile:'both',min:5};
let generation=0;
const monthLabel=s=>/^\d{4}-\d{2}$/.test(s)?new Date(+s.slice(0,4),+s.slice(5)-1,1).toLocaleDateString('pt-BR',{month:'long',year:'numeric'}):s;
const allNames=()=>[...new Set(state.rows.map(r=>r.technician))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
function baseRows(){return state.rows.filter(r=>state.clients.includes(r.client)&&(!state.measurement||r.measurement===state.measurement)&&(!state.pn||r.partNumber===state.pn)&&(!state.filterStatus||r.status===state.filterStatus)&&(!state.filterWarranty||(state.filterWarranty==='unknown'?r.warranty===null:r.warranty===(state.filterWarranty==='yes')))&&(!state.filterTester||r.tester===state.filterTester));}
function filtered(){return baseRows().filter(r=>state.team.has(r.technician)&&(!state.search||`${r.id} ${r.partNumber}`.toUpperCase().includes(state.search.toUpperCase())));}
function visibleRows(){const rows=filtered();return state.present?presentationRows(rows,state.selected,allNames()):rows;}
function sortedStats(rows=visibleRows()){return groupStats(rows).sort((a,b)=>(b[state.sort]??-1)-(a[state.sort]??-1)||b.repaired-a.repaired||a.name.localeCompare(b.name,'pt-BR'));}
const option=(value,label,selected)=>`<option value="${esc(value)}" ${selected===value?'selected':''}>${esc(label)}</option>`;
const metric=n=>`<span class="metric ${n===null?'none':n<.8?'below':''}">${percent(n)}</span>`;
const days=n=>n===null?'—':n.toLocaleString('pt-BR',{maximumFractionDigits:1})+' d';
const initials=name=>name.split(' ').slice(0,2).map(x=>x[0]).join('');
const chip=(name,value,label,checked)=>`<label class="chip"><input type="checkbox" name="${name}" value="${esc(value)}" ${checked?'checked':''}>${esc(label)}</label>`;
function kpi(label,value,note,highlight=false,progress=null){return `<div class="kpi ${highlight?'highlight':''}"><span class="label">${label}</span><b>${typeof value==='number'?value.toLocaleString('pt-BR'):value}</b><small>${note}</small>${progress!==null?`<div class="progress"><i style="width:${Math.min(100,progress*100)}%"></i></div>`:''}</div>`;}
function overview(){
 const rows=visibleRows(),s=statistics(rows),team=sortedStats(rows),comparison=state.compare.size?team.filter(t=>state.compare.has(t.name)):team;
 return `<div class="section-intro"><div><h2>Resultados da equipe</h2><p>Produção e reparabilidade no período selecionado</p></div><span class="scope-tag">${state.clients.map(k=>CLIENTS.find(c=>c.key===k)?.name).join(' + ')||'Selecione um cliente'}</span></div>
 <section class="results-hero"><div class="hero-main"><span class="hero-eyebrow">${state.present?'PRODUÇÃO DA EQUIPE':'VALOR PRODUZIDO'}</span><h2>${state.present?'Peças reparadas':'Peças reparadas fora de garantia'}</h2><div class="hero-value">${state.present?s.repaired.toLocaleString('pt-BR'):money(s.producedValue)}</div><p>${state.present?'Valores em reais ocultos durante a apresentação.':s.repaired.toLocaleString('pt-BR')+' peças reparadas no recorte. Soma dos valores informados nas reparadas fora de garantia.'}</p>${!state.present&&s.valueMissing?`<p class="financial-warning"><strong>Valor parcial confirmado.</strong> ${s.warrantyMissing} reparadas sem informação de garantia e ${s.repairValueMissing} fora de garantia sem valor informado. Essas peças continuam nos percentuais de reparabilidade.</p>`:''}</div><div class="hero-secondary">${[['Reparabilidade geral',s.general,s.denominator],['Reparabilidade real',s.real,s.realDenominator]].map(([label,value,base])=>`<div class="hero-rate"><label>${label}</label><strong>${percent(value)}</strong><div class="hero-meter"><i style="width:${(value??0)*100}%"></i></div><small>${s.repaired} reparadas ÷ ${base} peças${label.includes('geral')?' · meta 80%':''}</small></div>`).join('')}</div></section>
 <section class="kpis">${kpi('Peças analisadas',s.total,s.completed.toLocaleString('pt-BR')+' concluídas')}${kpi('Reparadas',s.repaired,s.irreparable+' irreparáveis')}${kpi('Exclusões da base real',s.excluded,'Motivos previstos por cliente')}${kpi('Tempo médio',days(s.avgDays),team.length+' técnicos no recorte')}</section>
 ${!state.present?moneyPanel(rows,team):''}
 <div class="grid2 overview-charts"><section class="card"><h2>Volume por cliente e status</h2>${volumeChart(rows,state.clients)}</section><section class="card"><h2>Reparabilidade por técnico</h2>${repairChart(team)}</section></div>
 <section class="card"><div class="cardhead"><h2>Comparativo consolidado</h2><span class="clienttag">Ordenação por indicador · meta geral 80%</span></div>${table(team)}<p class="footnote">Reparabilidade: somente reparadas e irreparáveis. As exclusões alteram apenas a base real.${!state.present?' Valor produzido: '+money(s.producedValue)+' em reparadas fora de garantia.':''}</p></section>
 <section class="card"><div class="cardhead"><h2>Comparação de técnicos</h2><div class="comparison-controls"><label>Status A<select id="statusA">${STATUSES.map(s=>option(s,s,state.statusA)).join('')}</select></label><label>Status B<select id="statusB">${STATUSES.map(s=>option(s,s,state.statusB)).join('')}</select></label></div></div><div class="comparechoices">${team.map(t=>chip('compare',t.name,t.name,state.compare.has(t.name))).join('')}</div>${comparisonChart(comparison,state.statusA,state.statusB)}<p class="footnote center">${state.compare.size?state.compare.size+' técnicos selecionados.':'Todos os técnicos do recorte. Selecione até seis para comparar.'}</p></section>`;
}
function moneyPanel(rows,team){
 const sorted=[...team].sort((a,b)=>b.producedValue-a.producedValue),max=Math.max(1,...sorted.map(t=>t.producedValue));
 return `<section class="card"><div class="cardhead"><div><h2>Valor das peças reparadas</h2><p>Produção por técnico e por cliente · fora de garantia</p></div><span class="clienttag">REAIS · R$</span></div><div class="money-panel"><div class="money-list">${sorted.map(t=>`<div class="money-row"><span>${esc(t.name)}</span><div class="track"><i style="width:${t.producedValue/max*100}%"></i></div><span class="amount">${money(t.producedValue)}</span></div>`).join('')||'<p class="empty">Nenhuma peça no recorte.</p>'}</div><div class="money-clients">${state.clients.map(key=>{const c=CLIENTS.find(c=>c.key===key),s=statistics(rows.filter(r=>r.client===key));return `<div class="money-client"><label>${esc(c.name)}</label><strong>${money(s.producedValue)}</strong><small>${s.repaired} reparadas · geral ${percent(s.general)}</small></div>`}).join('')}</div></div><p class="footnote">Não inclui sucatas nem peças em garantia. Valores ausentes não são estimados. Valor produzido não representa confirmação de faturamento ou recebimento.</p></section>`;
}
function table(team,firstLabel='Técnico'){
 if(!team.length)return '<p class="empty">Nenhum resultado neste recorte.</p>';
 const cols=[['total','Peças'],['completed','Concluídas'],['repaired','Reparadas'],['irreparable','Irreparáveis'],['noFault','Sem defeito'],['noAttempt','Sem reparo'],['excluded','Excluídas'],['general','Rep. geral'],['real','Rep. real'],['avgDays','Tempo médio']];
 if(!state.present)cols.push(['producedValue','Valor produzido']);
 const enriched=team.map(t=>({...t,noFault:t.counts['SEM DEFEITO'],noAttempt:t.counts['SEM REPARO']})).sort((a,b)=>(b[state.sort]??-1)-(a[state.sort]??-1)||b.repaired-a.repaired||a.name.localeCompare(b.name,'pt-BR'));
 return `<div class="tablewrap"><table><thead><tr><th>Ordem</th><th>${esc(firstLabel)}</th>${cols.map(([k,l])=>`<th><button class="sort" data-sort="${k}">${l}${state.sort===k?' ↓':''}</button></th>`).join('')}</tr></thead><tbody>${enriched.map((t,i)=>`<tr class="${state.present&&t.name===state.selected?'selected-row':''}"><td>${i+1}º</td><td class="namecol">${esc(t.name)}</td>${cols.map(([k])=>`<td>${['real','general'].includes(k)?metric(t[k]):k==='avgDays'?days(t[k]):k==='producedValue'?money(t[k]):t[k]}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
function partNumbers(){const rows=visibleRows(),groups=groupStats(rows,'partNumber');return `<section class="card"><div class="cardhead"><div><h2>Especialidades por Part Number</h2><p>Compare resultados em peças do mesmo modelo</p></div><label>Amostra mínima<select id="min">${[3,5,10,20].map(n=>option(String(n),`${n} tentativas`,String(state.min))).join('')}</select></label></div><div class="tablewrap"><table><thead><tr><th>Part Number</th><th>Peças</th><th>Reparadas</th><th>Irreparáveis</th><th>Excluídas</th><th>Geral</th><th>Real</th><th>Maior reparabilidade real*</th></tr></thead><tbody>${groups.map(g=>{const eligible=groupStats(rows.filter(r=>r.partNumber===g.name)).filter(t=>t.realDenominator>=state.min);const top=eligible[0];const tied=top?eligible.filter(t=>t.real===top.real):[];return `<tr><td><button class="btn text" data-pn="${esc(g.name)}">${esc(g.name)}</button></td><td>${g.total}</td><td>${g.repaired}</td><td>${g.irreparable}</td><td>${g.excluded}</td><td>${metric(g.general)}</td><td>${metric(g.real)}</td><td>${top?esc(tied.map(t=>t.name).join(' / ')):'Amostra insuficiente'}</td></tr>`}).join('')}</tbody></table></div><p class="footnote">* Entre técnicos com ao menos ${state.min} peças na base real deste Part Number. Empates são mantidos. Clique no Part Number para abrir o comparativo correspondente.</p></section>`;}
function trend(rows){const monthly=groupStats(rows,'measurement').sort((a,b)=>a.name.localeCompare(b.name));if(!monthly.length)return '<p class="empty">Sem medições neste recorte.</p>';const width=700,height=210,space=monthly.length>1?580/(monthly.length-1):0,px=i=>monthly.length>1?60+i*space:350,py=n=>170-(n??0)*135;return `<svg class="trend" viewBox="0 0 ${width} ${height}" role="img" aria-label="Evolução da reparabilidade por medição"><line x1="35" y1="${py(.8)}" x2="670" y2="${py(.8)}" stroke="#b6c4d5" stroke-dasharray="4 5"/><text x="5" y="${py(.8)+4}">80%</text>${['general','real'].map((k,j)=>{let segments=[];let current=[];monthly.forEach((m,i)=>{if(m[k]===null){if(current.length)segments.push(current);current=[];}else current.push(`${px(i)},${py(m[k])}`)});if(current.length)segments.push(current);return segments.map(points=>`<polyline fill="none" stroke="${j?'#0b846c':'#145bd8'}" stroke-width="2.5" points="${points.join(' ')}"/>`).join('')+monthly.map((m,i)=>m[k]===null?'':`<circle cx="${px(i)}" cy="${py(m[k])}" r="4" fill="${j?'#0b846c':'#145bd8'}"><title>${esc(monthLabel(m.name))}: ${k==='real'?'Real':'Geral'} ${percent(m[k])}</title></circle>`).join('')}).join('')}${monthly.map((m,i)=>`<text text-anchor="middle" x="${px(i)}" y="196">${esc(m.name)}</text>`).join('')}</svg>`;}
function individual(){const rows=visibleRows(),names=[...new Set(rows.map(r=>r.technician))].sort(),selected=state.present?state.selected:(names.includes(state.selected)?state.selected:names[0]);if(!selected)return '<section class="card empty">Nenhum técnico neste recorte.</section>';const own=rows.filter(r=>r.technician===selected),s=statistics(own),peers=statistics(rows.filter(r=>r.technician!==selected));return `<section class="card"><div class="cardhead"><div class="reporttitle"><span class="avatar">${esc(initials(selected))}</span><div><h2>${esc(selected)}</h2><p>Relatório individual · ${state.measurement?esc(monthLabel(state.measurement)):'todas as medições'}</p></div></div>${!state.present?`<label>Técnico<select id="reportTech">${names.map(n=>option(n,n,selected)).join('')}</select></label>`:''}</div><div class="subgrid"><div class="submetric"><small>Reparadas</small><b>${s.repaired}</b></div><div class="submetric"><small>Geral</small><b>${percent(s.general)}</b></div><div class="submetric"><small>Real</small><b>${percent(s.real)}</b></div><div class="submetric"><small>Tempo médio</small><b>${days(s.avgDays)}</b></div></div><p class="reportcopy">Foram analisadas <strong>${s.total} peças</strong>, com ${s.repaired} reparadas e ${s.irreparable} irreparáveis. Destas, ${s.excluded} têm motivo previsto de exclusão da base real. ${s.general===null?'Ainda não há reparadas ou irreparáveis para calcular a reparabilidade.':`A reparabilidade geral ${s.general>=.8?'atinge':'está abaixo da'} meta de 80%.`} ${peers.real!==null?`A reparabilidade real dos demais técnicos neste recorte é ${percent(peers.real)}.`:'Não há base comparável dos demais técnicos neste recorte.'}</p>${!state.present?`<p class="footnote">Valor produzido: ${money(s.producedValue)} · reparadas fora de garantia${s.valueMissing?' · '+s.valueMissing+' com informação financeira incompleta':''}.</p>`:''}</section><div class="grid2"><section class="card"><div class="cardhead"><h2>Evolução por medição</h2><div class="legend"><span>Geral</span><span class="real">Real</span></div></div>${trend(own)}</section><section class="card"><h2>Distribuição dos resultados</h2>${STATUSES.map((status,i)=>`<div class="barrow"><span>${status.toLowerCase()}</span><div class="track"><i style="width:${s.total?s.counts[status]/s.total*100:0}%;background:${colors[i]}"></i></div><b>${s.counts[status]}</b></div>`).join('')}</section></div><section class="card"><h2>Resultados por Part Number</h2>${table(groupStats(own,'partNumber'), 'Part Number')}<p class="footnote">O histórico é agrupado pela medição da base de origem. Alterações nessa base podem atualizar medições anteriores.</p></section>`;}
function rules(){return `<section class="card"><h2>Como calculamos</h2><div class="formula"><strong>Geral</strong> = reparadas ÷ (reparadas + irreparáveis)<br><strong>Real</strong> = reparadas ÷ (reparadas + irreparáveis − exclusões)</div><p>Meta contratual geral: <strong>80%</strong>. Em reparo, sem defeito e sem reparo não entram em nenhuma das duas bases. Sem denominador, mostramos “—”. Ao combinar clientes, somamos as contagens após aplicar as exclusões específicas.</p></section><div class="rules">${CLIENTS.filter(c=>state.allowed.includes(c.key)).map(c=>`<section class="card"><span class="eyebrow">${c.name}</span><h2>Exclusões da reparabilidade real</h2><p>Somente irreparáveis cuja <strong>Descrição do Reparo</strong>, coluna <strong>${c.column}</strong>, contenha:</p><ul>${c.exclusions.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></section>`).join('')}</div><section class="card"><h2>Detalhes da leitura</h2><p>Acentos, maiúsculas e espaços são normalizados. Não buscamos motivos em outras observações. As peças excluídas permanecem no total de sucatas e na reparabilidade geral. Valores em reais consideram apenas reparadas fora de garantia, com valor informado; não incluem triagem de irreparáveis.</p><p>Versão das regras: ${VERSION}. Novos clientes precisam ter sua origem e regras cadastradas antes de receberem permissões.</p></section>`;}
function accessPanel(){if(!state.canManage)return '';if(!state.access)return '<section class="card empty">Carregando as permissões…</section>';return `<section class="card"><div class="cardhead"><div><h2>Acesso por pessoa e cliente</h2><p>Somente sócios e administradores internos. Técnicos não têm acesso.</p></div></div><div class="access-grid"><div><label>Pessoa<select id="accessPerson"><option value="">Selecione uma pessoa</option>${state.access.users.map(u=>option(u.id,u.name||u.email,state.access.selected)).join('')}</select></label><p>O acesso ao aplicativo também precisa estar liberado no Portal. Um novo cliente não libera acesso automaticamente.</p></div><div id="accessChoices">${accessChoices()}</div></div><p id="accessMessage" role="status">${esc(state.access.message||'')}</p></section>`;}
function accessChoices(){const a=state.access;if(!a.selected)return '<p>Escolha uma pessoa para consultar as permissões.</p>';const grant=a.grants.find(g=>g.user_id===a.selected);return `<p>Clientes que esta pessoa pode consultar</p>${CLIENTS.map(c=>chip('grant',c.key,c.name,(grant?.clients||[]).includes(c.key))).join('')}<button id="saveAccess" class="btn">Salvar permissões</button>`;}
function render(){
 const names=allNames();
 const tabs=[['overview','Visão geral'],['pn','Análise por Part Number'],['individual','Relatório por técnico'],['rules','Regras de cálculo']];if(state.canManage&&!state.present)tabs.push(['access','Permissões']);
 $('app').setAttribute('aria-busy',String(state.loading));document.body.classList.toggle('presentation-active',state.present);
 $('app').innerHTML=`<div class="pagehead"><div class="header-identity"><img class="livion-logo" src="./livion-logo.svg" alt="Livion Solutions"><div><h1>Desempenho técnico consolidado</h1><p>Claro + Nokia · comparação, especialidade por Part Number e relatório individual</p></div></div><div class="actions">${state.present?'<button class="btn dark" id="exitPresent">Encerrar apresentação</button>':`<button class="btn dark" id="present" ${!names.length?'disabled':''}>▣ &nbsp; Modo apresentação</button>`}<button class="btn secondary" id="export" ${!state.rows.length?'disabled':''}>Exportar comparativo</button><button class="btn secondary" id="refresh" ${state.loading?'disabled':''}>↻ &nbsp; Atualizar</button></div></div>
 ${demo?`<div class="notice demo no-print"><span><strong>Prévia local · dados fictícios</strong> &nbsp; Nenhuma leitura das bases reais.</span>${!state.present?`<label style="margin:0">Simular acesso<select id="demoProfile">${option('both','Sócio · Claro + Nokia',state.demoProfile)}${option('claro','Sócio · somente Claro',state.demoProfile)}${option('nokia','Sócio · somente Nokia',state.demoProfile)}${option('admin','Administrador · gerenciar acessos',state.demoProfile)}</select></label>`:''}</div>`:''}
 ${state.present?`<div class="notice presentation"><span><strong>Apresentação para ${esc(state.selected)}</strong><br><small>Demais técnicos anônimos · todos os valores em reais ocultos</small></span><button class="btn secondary" id="print">Imprimir apresentação</button></div>`:''}
 ${state.error?`<div class="notice error" role="alert">${esc(state.error)}</div>`:''}
 <div class="filters"><div class="field"><span>CLIENTES</span><div class="clientchecks">${CLIENTS.filter(c=>state.allowed.includes(c.key)).map(c=>chip('client',c.key,c.name,state.clients.includes(c.key))).join('')||'<small>Nenhum cliente liberado</small>'}</div></div><label class="field">MEDIÇÃO<select id="measurement">${option('','Todas as medições',state.measurement)}${[...new Set(state.rows.filter(r=>state.clients.includes(r.client)).map(r=>r.measurement))].sort().reverse().map(m=>option(m,monthLabel(m),state.measurement)).join('')}</select></label><label class="field">PART NUMBER<select id="pnFilter">${option('','Todos os Part Numbers',state.pn)}${[...new Set(state.rows.filter(r=>state.clients.includes(r.client)).map(r=>r.partNumber))].sort().map(p=>option(p,p,state.pn)).join('')}</select></label><label class="field">STATUS<select id="filterStatus">${option('','Todos os status',state.filterStatus)}${STATUSES.map(s=>option(s,s,state.filterStatus)).join('')}</select></label><label class="field">GARANTIA<select id="filterWarranty">${option('','Todas as garantias',state.filterWarranty)}${option('yes','Em garantia',state.filterWarranty)}${option('no','Fora da garantia',state.filterWarranty)}${option('unknown','Não informado',state.filterWarranty)}</select></label>${!state.present?`<label class="field">TESTADO POR<select id="filterTester">${option('','Todos os testadores',state.filterTester)}${[...new Set(state.rows.filter(r=>state.clients.includes(r.client)).map(r=>r.tester))].sort().map(n=>option(n,n,state.filterTester)).join('')}</select></label>`:''}${!state.present?`<label class="field">BUSCAR ID OU PART NUMBER<input id="search" type="search" placeholder="Digite para buscar" value="${esc(state.search)}"></label>`:''}<button class="btn text" id="clear">Limpar filtros</button></div>
 ${!state.present?`<section class="choose"><div class="teamhead"><h2>Técnicos analisados</h2><div class="actions"><small>${state.team.size} selecionados</small><button class="btn secondary" id="allTech">Marcar todos</button><button class="btn secondary" id="noneTech">Desmarcar todos</button></div></div><div class="choices">${names.map(n=>chip('team',n,n,state.team.has(n))).join('')}</div></section>`:''}
 <nav class="nav" aria-label="Seções">${tabs.map(([key,label])=>`<button data-tab="${key}" class="${state.tab===key?'active':''}" aria-current="${state.tab===key?'page':'false'}">${label}</button>`).join('')}</nav>
 ${state.tab==='overview'?overview():state.tab==='pn'?partNumbers():state.tab==='individual'?individual():state.tab==='rules'?rules():accessPanel()}
 <footer class="bottom"><span class="source">${demo?'Demonstração':state.updated?'Leitura das bases':'Aguardando conexão'}${state.updated?' · '+esc(state.updated):''}</span><span>Livion Solutions · Regras ${VERSION}</span></footer>`;
 $('topbar').replaceChildren($('app').querySelector('.pagehead'));
 bind();
}
function bind(){
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=async()=>{state.tab=b.dataset.tab;render();if(state.tab==='access')await loadAccess()});
 document.querySelectorAll('input[name=client]').forEach(b=>b.onchange=()=>{state.clients=[...document.querySelectorAll('input[name=client]:checked')].map(x=>x.value);state.measurement='';state.pn='';render()});
 document.querySelectorAll('input[name=team]').forEach(b=>b.onchange=()=>{b.checked?state.team.add(b.value):state.team.delete(b.value);render()});
 document.querySelectorAll('input[name=compare]').forEach(b=>b.onchange=()=>{if(b.checked&&state.compare.size>=6){b.checked=false;return}b.checked?state.compare.add(b.value):state.compare.delete(b.value);render()});
 document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{state.sort=b.dataset.sort;render()});
 document.querySelectorAll('[data-pn]').forEach(b=>b.onclick=()=>{state.pn=b.dataset.pn;state.tab='overview';render();window.scrollTo(0,0)});
 if($('statusA'))$('statusA').onchange=e=>{state.statusA=e.target.value;render()};if($('statusB'))$('statusB').onchange=e=>{state.statusB=e.target.value;render()};
 for(const id of ['filterStatus','filterWarranty','filterTester'])if($(id))$(id).onchange=e=>{state[id]=e.target.value;render()};
 $('measurement').onchange=e=>{state.measurement=e.target.value;render()};$('pnFilter').onchange=e=>{state.pn=e.target.value;render()};
 if($('search'))$('search').onchange=e=>{state.search=e.target.value;render()};
 $('clear').onclick=()=>{state.measurement='';state.pn='';state.filterStatus='';state.filterWarranty='';state.filterTester='';state.search='';state.clients=[...state.allowed];render()};
 if($('allTech'))$('allTech').onclick=()=>{state.team=new Set(allNames());render()};if($('noneTech'))$('noneTech').onclick=()=>{state.team.clear();render()};
 if($('present'))$('present').onclick=()=>{const names=allNames();$('presentTech').innerHTML=names.map(n=>option(n,n,state.selected)).join('');$('presentDialog').showModal()};
 if($('exitPresent'))$('exitPresent').onclick=()=>$('exitDialog').showModal();
 if($('print'))$('print').onclick=()=>window.print();
 $('refresh').onclick=()=>refresh();$('export').onclick=exportComparison;
 if($('min'))$('min').onchange=e=>{state.min=Number(e.target.value);render()};
 if($('reportTech'))$('reportTech').onchange=e=>{state.selected=e.target.value;render()};
 if($('demoProfile'))$('demoProfile').onchange=e=>{state.demoProfile=e.target.value;state.access=null;state.tab='overview';refresh()};
 if($('accessPerson'))$('accessPerson').onchange=e=>{state.access.selected=e.target.value;state.access.message='';render()};
 if($('saveAccess'))$('saveAccess').onclick=saveAccess;
}
$('presentDialog').addEventListener('close',()=>{if($('presentDialog').returnValue!=='confirm')return;state.selected=$('presentTech').value;state.present=true;state.filterTester='';state.sort='real';state.search='';state.team=new Set(allNames());state.compare.clear();state.access=null;state.tab='individual';$('presentTech').replaceChildren();render()});
$('exitDialog').addEventListener('close',()=>{if($('exitDialog').returnValue==='confirm'){state.present=false;state.compare.clear();render()}});
function exportComparison(){const blob=new Blob([comparisonCSV(sortedStats(),state.present)],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.present?'Apresentacao_Desempenho.csv':'Comparativo_Desempenho.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000);}
function token(){try{if(parent!==window&&parent.location.origin===location.origin)return parent.__PORTAL_TOKEN__||'';}catch{}return '';}
async function request(path,options={}){const t=token();if(!t)throw new Error('Abra este aplicativo pelo Portal Livion com sua conta autorizada.');const response=await fetch(endpoint+path,{...options,cache:'no-store',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},signal:AbortSignal.timeout(90000)});const body=await response.json();if(!response.ok){const error=new Error(response.status===403?'Sua conta não tem acesso a este aplicativo ou cliente.':response.status===401?'Sua sessão expirou. Entre novamente pelo Portal.':body.message||'Não foi possível consultar os dados.');error.status=response.status;throw error}return body;}
async function refresh(){if(state.loading)return;state.loading=true;state.error='';const ticket=++generation;render();try{
 let payload;
 if(demo){const {demoRows}=await import('./demo.mjs');const allowed=['claro','nokia'].filter(c=>!['claro','nokia'].includes(state.demoProfile)||c===state.demoProfile);payload={rows:demoRows().filter(r=>allowed.includes(r.client)),clients:allowed,canManage:state.demoProfile==='admin',updatedAt:new Date().toISOString()};}
 else payload=await request('/data');
 if(ticket!==generation)return;
 if(!Array.isArray(payload.rows)||!Array.isArray(payload.clients)||payload.rows.some(r=>!payload.clients.includes(r.client)))throw new Error('Resposta de dados inválida.');
 const oldNames=new Set(allNames()),oldClients=state.allowed;state.rows=payload.rows;state.allowed=payload.clients;state.canManage=payload.canManage===true;state.clients=oldClients.length?state.clients.filter(c=>state.allowed.includes(c)):state.allowed.slice();
 if(!state.clients.length&&state.allowed.length)state.clients=state.allowed.slice();
 state.team=new Set(allNames().filter(n=>state.team.has(n)||!oldNames.has(n)));state.updated=new Date(payload.updatedAt).toLocaleString('pt-BR');
 if(state.present&&!allNames().includes(state.selected)){state.rows=[];throw new Error('O técnico apresentado não está mais disponível. Encerre a apresentação para atualizar a seleção.');}
 if(!state.canManage&&state.tab==='access'){state.access=null;state.tab='overview';}
 }catch(error){state.rows=[];state.allowed=[];state.clients=[];state.team.clear();state.compare.clear();state.access=null;state.canManage=false;state.updated='';state.error=error.name==='TimeoutError'?'A leitura demorou além do esperado. Tente atualizar novamente.':error.message;}finally{state.loading=false;render()}}
async function loadAccess(){try{if(demo){state.access||={users:[{id:'demo-partner-1',name:'Sócio fictício 1'},{id:'demo-partner-2',name:'Sócio fictício 2'}],grants:[{user_id:'demo-partner-1',clients:['claro'],revision:1},{user_id:'demo-partner-2',clients:['claro','nokia'],revision:1}]};}else state.access=await request('/access');render();}catch(e){state.error=e.message;render()}}
async function saveAccess(){const id=state.access.selected,clients=[...document.querySelectorAll('input[name=grant]:checked')].map(x=>x.value);const old=state.access.grants.find(g=>g.user_id===id);$('saveAccess').disabled=true;try{if(demo){state.access.grants=state.access.grants.filter(g=>g.user_id!==id).concat({user_id:id,clients,revision:(old?.revision||0)+1});state.access.message='Permissão fictícia salva nesta sessão de demonstração.';}else{await request('/access',{method:'PUT',body:JSON.stringify({user_id:id,clients,revision:old?.revision??0})});const read=await request('/access');const grant=read.grants.find(g=>g.user_id===id);if(JSON.stringify([...(grant?.clients||[])].sort())!==JSON.stringify([...clients].sort()))throw new Error('A releitura não confirmou a seleção. Recarregue as permissões.');state.access={...read,selected:id,message:'Permissões salvas e confirmadas.'};}render();}catch(e){state.access.message=e.message;render()}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!demo)refresh()});
window.addEventListener('pagehide',()=>{state.rows=[];state.access=null;$('app').replaceChildren()});
window.addEventListener('pageshow',e=>{if(e.persisted)refresh()});
refresh();setInterval(()=>{if(!document.hidden&&!demo)refresh()},60000);




