import { createClient } from 'jsr:@supabase/supabase-js@2';
import seed from './seed.json' with { type: 'json' };

const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const TENANT='911e1aee-070e-421b-ae71-439f01c2263e',CLIENT='88cf5cba-9f67-467d-8a51-9638200bed52',APP='vtal';
const origins=new Set(['https://portal.livionsolutions.com.br','http://localhost:3000','http://localhost:5173']);
const statuses=new Set(['ready','partial','no','question','attention']);
function headers(origin:string|null){return{'Access-Control-Allow-Origin':origin&&origins.has(origin)?origin:'https://portal.livionsolutions.com.br','Vary':'Origin','Access-Control-Allow-Headers':'authorization,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Content-Type':'application/json','Cache-Control':'no-store'}}
const reply=(origin:string|null,body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:headers(origin)});
function jwt(token:string){try{return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')))}catch{return{}}}
async function auth(req:Request){const token=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,''),claims=jwt(token);if(!token||claims.tid!==TENANT||(claims.azp!==CLIENT&&claims.appid!==CLIENT))throw Error('UNAUTHORIZED');const graph=await fetch('https://graph.microsoft.com/v1.0/me?$select=id,displayName,mail,userPrincipalName',{headers:{authorization:`Bearer ${token}`}});if(!graph.ok)throw Error('UNAUTHORIZED');const me=await graph.json(),email=String(me.mail||me.userPrincipalName||'').trim().toLowerCase();let q=await db.from('portal_users').select('*').eq('microsoft_id',String(me.id)).maybeSingle();if(!q.data)q=await db.from('portal_users').select('*').ilike('email',email).maybeSingle();const user=q.data,admin=user?.profile==='ADMINISTRADOR',apps=Array.isArray(user?.apps)?user.apps:[],actions=Array.isArray(user?.actions)?user.actions:[];if(!user?.active||String(user.user_type||'INTERNO').toUpperCase()!=='INTERNO'||(!admin&&!apps.includes(APP)))throw Error('FORBIDDEN');return{user,email,admin,actions}}
const can=(a:any,key:string)=>a.admin||a.actions.includes(key),need=(a:any,key:string)=>{if(!can(a,key))throw Error('FORBIDDEN')};
async function current(){const q=await db.from('vtal_checklists').select('*').eq('id','rfp').maybeSingle();if(q.error)throw q.error;return q.data||null}
function payload(row:any){return row?.payload||seed}
function validateItem(value:any,groups:any[]){if(!value||typeof value!=='object')throw Error('INVALID_ITEM');const text=(key:string,max:number,required=false)=>{const v=value[key];if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw Error('INVALID_ITEM');return v.trim()};const item={id:text('id',80,true),group:text('group',80,true),text:text('text',4000,true),notes:text('notes',8000),owner:text('owner',160),status:value.status,order:value.order,archived:value.archived};if(!groups.some(g=>g.id===item.group)||!(item.status===null||statuses.has(item.status))||!Number.isSafeInteger(item.order)||item.order<0||typeof item.archived!=='boolean')throw Error('INVALID_ITEM');return item}
function response(a:any,row:any){const p=payload(row);return{groups:p.groups,items:p.items,revision:Number(row?.revision||0),updated_at:row?.updated_at||null,updated_by:row?.updated_by||null,permissions:{edit:can(a,'vtal.editar'),export:can(a,'vtal.exportar')}}}
async function saveItem(a:any,b:any){need(a,'vtal.editar');const row=await current(),revision=Number(b.revision);if(revision!==Number(row?.revision||0))throw Error('CONFLICT');const base=structuredClone(payload(row)),item=validateItem(b.item,base.groups),index=base.items.findIndex((x:any)=>x.id===item.id);if(index>=0)base.items[index]=item;else{if(!item.id.startsWith('NOVO-')||base.items.length>=2000)throw Error('INVALID_ITEM');base.items.push(item)}const now=new Date().toISOString();let saved:any;if(row){const q=await db.from('vtal_checklists').update({payload:base,revision:revision+1,updated_at:now,updated_by:a.email}).eq('id','rfp').eq('revision',revision).select('*').maybeSingle();if(q.error)throw q.error;if(!q.data)throw Error('CONFLICT');saved=q.data}else{const q=await db.from('vtal_checklists').insert({id:'rfp',payload:base,revision:1,updated_at:now,updated_by:a.email}).select('*').single();if(q.error){if(q.error.code==='23505')throw Error('CONFLICT');throw q.error}saved=q.data}await db.from('access_audit').insert({actor_email:a.email,action:'VTAL_ITEM_UPSERT',target:item.id,detail:{revision:saved.revision,status:item.status,archived:item.archived}});return response(a,saved)}
Deno.serve(async req=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(origin)});let a:any;try{a=await auth(req);const path=new URL(req.url).pathname.split('/').pop();if(req.method==='GET'&&path==='health')return reply(origin,{ok:true,service:'vtal-api',version:1});if(req.method==='GET'&&path==='bootstrap'){need(a,'vtal.visualizar');return reply(origin,response(a,await current()))}if(req.method==='GET'&&path==='export'){need(a,'vtal.exportar');return reply(origin,{ok:true})}if(req.method==='POST'&&path==='item')return reply(origin,await saveItem(a,await req.json()));return reply(origin,{error:'NOT_FOUND'},404)}catch(error){const message=String(error?.message||error),status=message.includes('UNAUTHORIZED')?401:message.includes('FORBIDDEN')?403:message.includes('CONFLICT')?409:message.includes('INVALID')?400:500;if(a&&status===403)await db.from('access_audit').insert({actor_email:a.email,action:'VTAL_ACCESS_DENIED',target:'vtal-api',detail:{message}}).catch(()=>{});return reply(origin,{error:message},status)}});
