from pathlib import Path

js_path=Path('despesas-reembolsos-v2.js')
html_path=Path('despesas-reembolsos-v2.html')
js=js_path.read_text(encoding='utf-8')
html=html_path.read_text(encoding='utf-8')

old_parser=r'''function brMoney(v){const m=String(v||'').match(/(?:R\$\s*)?([\d.]+,\d{2})/g);if(!m?.length)return null;const s=m[m.length-1].replace(/R\$\s*/i,'').replace(/\./g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:null}
function chooseVendor(lines,cnpjIndex){const bad=/DOCUMENTO|AUXILIAR|NFC|NF-E|CNPJ|CPF|CONSUMIDOR|CHAVE|CUPOM|EXTRATO|SAT|SEFAZ/i;for(let i=Math.max(0,cnpjIndex-1);i>=Math.max(0,cnpjIndex-4);i--){const s=lines[i];if(s&&s.length>3&&!bad.test(s)&&!/^\d/.test(s))return s}return lines.find(s=>s.length>4&&!bad.test(s)&&/[A-Za-zÁ-ú]/.test(s))||''}
function parseFiscalText(text,qr=''){const lines=String(text||'').split(/\r?\n/).map(s=>s.replace(/\s+/g,' ').trim()).filter(Boolean),joined=lines.join('\n'),key=parseKey(qr+' '+joined),cnpjMatch=joined.match(/\d{2}\.?\d{3}\.?\d{3}\/?\d{4}-?\d{2}/),cnpj=key.cnpj||digits(cnpjMatch?.[0]||''),cnpjIndex=lines.findIndex(l=>digits(l).includes(cnpj)&&cnpj),addr=lines.find(l=>/\b(RUA|AVENIDA|AV\.?|RODOVIA|ROD\.?|ESTRADA|ALAMEDA|PRA[CÇ]A)\b/i.test(l))||'',dateMatch=joined.match(/\b(\d{2}[\/.-]\d{2}[\/.-]\d{4})(?:\s+(\d{2}:\d{2}(?::\d{2})?))?/),totalLine=lines.filter(l=>/TOTAL|VALOR A PAGAR/i.test(l)&&!/TRIBUT|ICMS|TROCO|DESCONTO|SUBTOTAL|ITENS/i.test(l)).reverse().find(l=>brMoney(l)!=null)||'',payLine=lines.find(l=>/PIX|CR[EÉ]DITO|D[EÉ]BITO|DINHEIRO/i.test(l))||'',numMatch=joined.match(/(?:N[ÚU]MERO|N[ºO]\.?|NFC-E|NF-E)[^\d]{0,10}(\d{1,9})/i);return{establishment:chooseVendor(lines,cnpjIndex),cnpj,address:addr,number:key.number||numMatch?.[1]||'',series:key.series||'',access_key:key.access_key||'',date_time:dateMatch?`${dateMatch[1]}${dateMatch[2]?' '+dateMatch[2]:''}`:'',value:brMoney(totalLine),payment_method:payLine,official_query_url:qr||'',ocr_text:joined.slice(0,8000)}}'''

new_parser=r'''function numericOcr(v){return String(v||'').replace(/[OoQq]/g,'0').replace(/[Il|!]/g,'1').replace(/[Zz]/g,'2').replace(/[Ss]/g,'5').replace(/[Gg]/g,'6').replace(/B/g,'8')}
function moneyTokens(v){const s=numericOcr(v).replace(/R\s*\$/gi,'R$');const hits=s.match(/(?:R\$\s*)?\d{1,3}(?:[.\s]\d{3})*[,.]\d{2}|(?:R\$\s*)?\d+[,.]\d{2}/g)||[];return hits.map(x=>{const raw=x.replace(/R\$\s*/i,'').replace(/\s/g,'');const comma=raw.lastIndexOf(','),dot=raw.lastIndexOf('.'),dec=Math.max(comma,dot),whole=dec>=0?raw.slice(0,dec).replace(/[.,]/g,''):raw.replace(/[.,]/g,''),frac=dec>=0?raw.slice(dec+1).replace(/\D/g,'').slice(0,2):'00',n=Number(whole+'.'+frac.padEnd(2,'0'));return Number.isFinite(n)?n:null}).filter(n=>n!=null)}
function brMoney(v){const m=moneyTokens(v);return m.length?m[m.length-1]:null}
function validCnpj(v){const n=digits(v);if(n.length!==14||/^(\d)\1{13}$/.test(n))return false;const calc=len=>{let sum=0,pos=len-7;for(let i=0;i<len;i++){sum+=Number(n[i])*pos--;if(pos<2)pos=9}const r=sum%11;return r<2?0:11-r};return calc(12)===Number(n[12])&&calc(13)===Number(n[13])}
function extractAccessKey(text){const raw=String(text||''),candidates=[];for(const line of raw.split(/\r?\n/)){const n=numericOcr(line).replace(/\D/g,'');if(n.length===44)candidates.push(n);if(n.length>44&&/CHAVE|ACESSO|NFC|NF-E/i.test(line)){for(let i=0;i<=n.length-44;i++)candidates.push(n.slice(i,i+44))}}const flat=numericOcr(raw).replace(/[^0-9\n]/g,'');for(const line of flat.split('\n'))if(line.length===44)candidates.push(line);return candidates.find(k=>/^\d{44}$/.test(k))||''}
function extractCnpj(lines,keyCnpj=''){if(keyCnpj&&keyCnpj.length===14)return keyCnpj;const preferred=lines.filter(l=>/CNPJ/i.test(l));for(const group of [preferred,lines])for(const line of group){const n=numericOcr(line).replace(/\D/g,'');for(let i=0;i<=n.length-14;i++){const c=n.slice(i,i+14);if(validCnpj(c))return c}}return''}
function chooseVendor(lines,cnpjIndex){const bad=/DOCUMENTO|AUXILIAR|NFC|NF-E|CNPJ|CPF|CONSUMIDOR|CHAVE|CUPOM|EXTRATO|SAT|SEFAZ|PROTOCOLO|AUTORIZA[CÇ][AÃ]O|TOTAL/i;for(let i=Math.max(0,cnpjIndex-1);i>=Math.max(0,cnpjIndex-5);i--){const s=lines[i];if(s&&s.length>3&&!bad.test(s)&&!/^\s*[\d.,/-]+\s*$/.test(s))return s}return lines.find(s=>s.length>4&&!bad.test(s)&&/[A-Za-zÁ-ú]/.test(s))||''}
function extractTotal(lines){let best=null,bestScore=-999;for(const line of lines){const vals=moneyTokens(line);if(!vals.length)continue;let score=0;if(/VALOR\s+TOTAL|TOTAL\s+(?:DA\s+)?NOTA|TOTAL\s+A\s+PAGAR|VALOR\s+A\s+PAGAR|VLR\.?\s*TOTAL/i.test(line))score+=120;else if(/^\s*TOTAL\b/i.test(line))score+=95;else if(/\bTOTAL\b/i.test(line))score+=60;if(/TRIBUT|ICMS|ISS|IMPOST|TROCO|DESCONTO|SUBTOTAL|ITENS|QTDE|UNIT[AÁ]RIO|BASE\s+DE\s+C[AÁ]LCULO/i.test(line))score-=100;const v=Math.max(...vals);if(score>bestScore&&v>0){best=v;bestScore=score}}if(bestScore>=40)return best;const all=lines.flatMap(moneyTokens).filter(v=>v>0&&v<1000000);return all.length?Math.max(...all):null}
function extractDate(text){const normalized=numericOcr(text);const m=normalized.match(/\b([0-3]\d)[\/.-]([01]\d)[\/.-](20\d{2}|\d{2})(?:\s+(?:[A-Za-z]{0,4}\s*)?([0-2]\d)[:h.]([0-5]\d)(?::([0-5]\d))?)?/);if(!m)return'';const y=m[3].length===2?'20'+m[3]:m[3],time=m[4]?` ${m[4]}:${m[5]}${m[6]?':'+m[6]:''}`:'';return`${m[1]}/${m[2]}/${y}${time}`}
function extractNumberSeries(lines,key){let number=key.number||'',series=key.series||'';for(const line of lines){if(!number&&/(?:N[ÚU]MERO|N[º°O]\.?|NFC-?E|NF-?E)/i.test(line)){const n=numericOcr(line),m=n.match(/(?:N[ÚU]MERO|N[º°O]\.?|NFC-?E|NF-?E)[^0-9]{0,14}(\d{1,9})/i);if(m)number=String(Number(m[1]))}if(!series&&/S[EÉ]RIE/i.test(line)){const n=numericOcr(line),m=n.match(/S[EÉ]RIE[^0-9]{0,8}(\d{1,3})/i);if(m)series=String(Number(m[1]))}}return{number,series}}
function parseFiscalText(text,qr=''){const lines=String(text||'').split(/\r?\n/).map(s=>s.replace(/\s+/g,' ').trim()).filter(Boolean),joined=lines.join('\n'),ocrKey=extractAccessKey(joined),key=parseKey(qr+' '+ocrKey),cnpj=extractCnpj(lines,key.cnpj||''),cnpjIndex=lines.findIndex(l=>cnpj&&numericOcr(l).replace(/\D/g,'').includes(cnpj)),addr=lines.find(l=>/\b(RUA|AVENIDA|AV\.?|RODOVIA|ROD\.?|ESTRADA|ALAMEDA|PRA[CÇ]A|TRAVESSA)\b/i.test(l))||'',payLine=lines.find(l=>/PIX|CR[EÉ]DITO|D[EÉ]BITO|DINHEIRO|CART[AÃ]O/i.test(l))||'',ns=extractNumberSeries(lines,key);return{establishment:chooseVendor(lines,cnpjIndex),cnpj,address:addr,number:ns.number||'',series:ns.series||'',access_key:key.access_key||ocrKey||'',date_time:extractDate(joined),value:extractTotal(lines),payment_method:payLine,official_query_url:qr||'',ocr_text:joined.slice(0,12000)}}
function fiscalScore(x){let s=0;if(x.access_key?.length===44)s+=6;if(validCnpj(x.cnpj||''))s+=5;if(x.value>0)s+=4;if(x.date_time)s+=3;if(x.number)s+=2;if(x.series)s+=1;if(x.establishment)s+=2;if(x.address)s+=1;if(x.payment_method)s+=1;return s}
function mergeFiscalReads(a,b){const first=fiscalScore(a)>=fiscalScore(b)?a:b,second=first===a?b:a,out={...first};for(const k of ['establishment','cnpj','address','number','series','access_key','date_time','value','payment_method','official_query_url'])if((out[k]==null||out[k]==='')&&second[k]!=null&&second[k]!=='')out[k]=second[k];if(!validCnpj(out.cnpj||'')&&validCnpj(second.cnpj||''))out.cnpj=second.cnpj;if(!(out.value>0)&&second.value>0)out.value=second.value;out.ocr_text=[a.ocr_text,b.ocr_text].filter(Boolean).join('\n--- OCR PASS ---\n').slice(0,16000);return out}'''

if old_parser not in js:
    raise SystemExit('Parser OCR antigo nao encontrado')
js=js.replace(old_parser,new_parser,1)

old_ocr=r'''async function loadTesseract(){if(window.Tesseract)return window.Tesseract;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)});return window.Tesseract}
async function scanFiscal(file){if(!file)return;$('scanStatus').textContent='Lendo nota fiscal…';let qr='',qrUsed=false,ocrUsed=false;try{if('BarcodeDetector'in window){const detector=new BarcodeDetector({formats:['qr_code']}),bmp=await createImageBitmap(file),codes=await detector.detect(bmp);qr=codes?.[0]?.rawValue||'';qrUsed=Boolean(qr)}}catch(e){console.warn('QR',e)}let text='';try{const T=await loadTesseract();const result=await T.recognize(file,'por',{logger:m=>{if(m.status==='recognizing text')$('scanStatus').textContent=`Lendo texto da nota… ${Math.round((m.progress||0)*100)}%`}});text=result?.data?.text||'';ocrUsed=Boolean(text.trim())}catch(e){console.warn('OCR',e)}const parsed=parseFiscalText(text,qr);parsed.qr_used=qrUsed;parsed.ocr_used=ocrUsed;fillFiscal(parsed,true);$('scanStatus').textContent=(qrUsed||ocrUsed)?'Leitura concluída. Confira os dados antes de salvar.':'Não consegui ler automaticamente. Você ainda pode anexar a nota e preencher os dados manualmente.'}'''

new_ocr=r'''async function loadTesseract(){if(window.Tesseract)return window.Tesseract;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=res;s.onerror=rej;document.head.appendChild(s)});return window.Tesseract}
async function receiptCanvas(file,threshold=false){let bmp;try{bmp=await createImageBitmap(file,{imageOrientation:'from-image'})}catch{bmp=await createImageBitmap(file)}const targetWidth=Math.min(2400,Math.max(1600,bmp.width)),scale=Math.min(2.5,targetWidth/bmp.width),w=Math.round(bmp.width*scale),h=Math.round(bmp.height*scale),c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(bmp,0,0,w,h);const img=ctx.getImageData(0,0,w,h),d=img.data;let sum=0;for(let i=0;i<d.length;i+=4){const g=.299*d[i]+.587*d[i+1]+.114*d[i+2];sum+=g}const mean=sum/(d.length/4),cut=Math.max(135,Math.min(210,mean*.88));for(let i=0;i<d.length;i+=4){let g=.299*d[i]+.587*d[i+1]+.114*d[i+2];g=Math.max(0,Math.min(255,(g-128)*1.75+142));if(threshold)g=g>cut?255:0;d[i]=d[i+1]=d[i+2]=g;d[i+3]=255}ctx.putImageData(img,0,0);return c}
async function runReceiptOcr(T,image,pass){const worker=await T.createWorker('por',1,{logger:m=>{if(m.status==='recognizing text')$('scanStatus').textContent=`OCR ${pass}/2… ${Math.round((m.progress||0)*100)}%`}});try{await worker.setParameters({tessedit_pageseg_mode:pass===1?'6':'11',preserve_interword_spaces:'1',user_defined_dpi:'300'});const r=await worker.recognize(image);return{text:r?.data?.text||'',confidence:Number(r?.data?.confidence||0)}}finally{await worker.terminate().catch(()=>{})}}
async function scanFiscal(file){if(!file)return;$('scanStatus').textContent='Preparando foto para leitura…';let qr='',qrUsed=false;try{if('BarcodeDetector'in window){const detector=new BarcodeDetector({formats:['qr_code']}),bmp=await createImageBitmap(file),codes=await detector.detect(bmp);qr=codes?.[0]?.rawValue||'';qrUsed=Boolean(qr)}}catch(e){console.warn('QR na foto',e)}let r1={text:'',confidence:0},r2={text:'',confidence:0};try{const T=await loadTesseract(),img1=await receiptCanvas(file,false),img2=await receiptCanvas(file,true);r1=await runReceiptOcr(T,img1,1);r2=await runReceiptOcr(T,img2,2)}catch(e){console.error('OCR fiscal',e);$('scanStatus').textContent='Falha no OCR: '+e.message;return}const p1=parseFiscalText(r1.text,qr),p2=parseFiscalText(r2.text,qr),parsed=mergeFiscalReads(p1,p2);parsed.qr_used=qrUsed;parsed.ocr_used=Boolean(r1.text.trim()||r2.text.trim());parsed.ocr_confidence=Math.max(r1.confidence,r2.confidence);fillFiscal(parsed,true);const found=[parsed.establishment&&'estabelecimento',parsed.cnpj&&'CNPJ',parsed.value>0&&'valor',parsed.date_time&&'data',parsed.number&&'número'].filter(Boolean);$('scanStatus').textContent=found.length?`OCR concluído. Identifiquei ${found.join(', ')}. Confira os dados antes de salvar.`:'OCR concluído, mas não encontrei campos fiscais confiáveis. Tente o QR Code ou uma foto mais próxima, reta e bem iluminada.'}'''

if old_ocr not in js:
    raise SystemExit('OCR antigo nao encontrado')
js=js.replace(old_ocr,new_ocr,1)

html=html.replace('Fotografar nota:</b> usa OCR como alternativa.','Fotografar nota:</b> usa OCR aprimorado. Para melhor resultado, fotografe a nota reta, ocupando a maior parte da tela e sem sombras.')
html=html.replace('./despesas-reembolsos-v2.js?v=4','./despesas-reembolsos-v2.js?v=5')

js_path.write_text(js,encoding='utf-8')
html_path.write_text(html,encoding='utf-8')
print('Enhanced receipt OCR applied')
