from pathlib import Path
import re

js_path=Path('despesas-reembolsos-v2.js')
html_path=Path('despesas-reembolsos-v2.html')
js=js_path.read_text(encoding='utf-8')
html=html_path.read_text(encoding='utf-8')

# Stronger vendor validation: never accept tiny OCR fragments such as "PE DE :".
old="function validFiscalVendor(v){const s=String(v||'').trim();return Boolean(s)&&!/(?:DATA\\s*\\/?\\s*HORA|DATA\\s+DE\\s+EMISS|EMISS[AÃ]O|AUTORIZA[CÇ][AÃ]O|PROTOCOLO|INFORMA[CÇ][ÕO]ES?\\s+DE\\s+INTERESSE|CONTRIBUINTE|DOCUMENTO\\s+AUXILIAR|CONSULTA|CHAVE\\s+DE\\s+ACESSO|^\\d{2}[\\/.-]\\d{2}[\\/.-]\\d{4})/i.test(s)}"
new="function validFiscalVendor(v){const s=String(v||'').replace(/\\s+/g,' ').trim();if(!s||/(?:DATA\\s*\\/?\\s*HORA|DATA\\s+DE\\s+EMISS|EMISS[AÃ]O|AUTORIZA[CÇ][AÃ]O|PROTOCOLO|INFORMA[CÇ][ÕO]ES?\\s+DE\\s+INTERESSE|CONTRIBUINTE|DOCUMENTO\\s+AUXILIAR|CONSULTA|CHAVE\\s+DE\\s+ACESSO|VALOR|VIA CLIENTE|\\bPOS\\b|\\bDOC\\b|^\\d{2}[\\/.-]\\d{2}[\\/.-](?:\\d{2}|\\d{4}))/i.test(s))return false;const letters=(s.match(/[A-Za-zÀ-ÿ]/g)||[]).length;if(letters<5||letters/Math.max(s.length,1)<.5)return false;const words=s.replace(/[^A-Za-zÀ-ÿ0-9 ]/g,' ').trim().split(/\\s+/).filter(Boolean);if(words.length<2&&letters<10)return false;return true}"
if old not in js: raise SystemExit('validFiscalVendor anchor not found')
js=js.replace(old,new,1)

# Replace vendorCandidate with the same stricter quality guard.
pattern=r"function vendorCandidate\(s\)\{.*?\}\nfunction chooseVendor"
replacement=r'''function vendorCandidate(s){const v=String(s||'').replace(/\s+/g,' ').trim(),bad=/DOCUMENTO|AUXILIAR|NFC|NF-E|CNPJ|CPF|CONSUMIDOR|CHAVE|CUPOM|EXTRATO|SAT|SEFAZ|VIA CLIENTE|CR[EÉ]DITO|D[EÉ]BITO|VISA|MASTERCARD|ELO\b|AMEX|POS\s*[=: -]|DOC\s*[=: -]|VALOR|APP\b|AUTORIZA[CÇ][AÃ]O|NSU\b/i;if(v.length<5||v.length>90||bad.test(v)||/^\d/.test(v))return'';const letters=(v.match(/[A-Za-zÀ-ÿ]/g)||[]).length,words=v.replace(/[^A-Za-zÀ-ÿ0-9 ]/g,' ').trim().split(/\s+/).filter(Boolean);if(letters<5||letters/Math.max(v.length,1)<.5||(words.length<2&&letters<10))return'';return v}
function chooseVendor'''
js,n=re.subn(pattern,lambda m:replacement,js,count=1,flags=re.S)
if n!=1: raise SystemExit(f'vendorCandidate replacement count={n}')

# Insert robust OCR helpers before scanFiscal.
anchor="async function scanFiscal(file){"
if anchor not in js: raise SystemExit('scanFiscal anchor not found')
helpers=r'''function ocrDigitFix(v){return String(v||'').toUpperCase().replace(/[OQD]/g,'0').replace(/[IL|]/g,'1').replace(/Z/g,'2').replace(/S/g,'5').replace(/G/g,'6').replace(/B/g,'8')}
function findOcrDateTime(text){const s=String(text||''),rx=/([0-9OQDIL|ZSBG]{1,2})[\/.\-]([0-9OQDIL|ZSBG]{1,2})[\/.\-]([0-9OQDIL|ZSBG]{2,4})(?:\s+([0-9OQDIL|ZSBG]{1,2})[:.]([0-9OQDIL|ZSBG]{2})(?::([0-9OQDIL|ZSBG]{2}))?)?/gi;for(const m of s.matchAll(rx)){const d=Number(ocrDigitFix(m[1])),mo=Number(ocrDigitFix(m[2]));let y=Number(ocrDigitFix(m[3]));if(String(ocrDigitFix(m[3])).length===2)y=y>=70?1900+y:2000+y;const hh=m[4]!=null?Number(ocrDigitFix(m[4])):12,mm=m[5]!=null?Number(ocrDigitFix(m[5])):0;if(d>=1&&d<=31&&mo>=1&&mo<=12&&y>=2000&&y<=2100&&hh>=0&&hh<=23&&mm>=0&&mm<=59)return `${String(d).padStart(2,'0')}/${String(mo).padStart(2,'0')}/${y} ${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}`}return''}
async function prepareOcrImage(file,strong=false){const bmp=await createImageBitmap(file),srcMax=Math.max(bmp.width,bmp.height),target=strong?2800:2400,scale=Math.max(1,Math.min(3,target/srcMax)),c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);const ctx=c.getContext('2d',{willReadFrequently:true});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(bmp,0,0,c.width,c.height);const im=ctx.getImageData(0,0,c.width,c.height),p=im.data,hist=new Uint32Array(256);for(let i=0;i<p.length;i+=4){const y=Math.round(.299*p[i]+.587*p[i+1]+.114*p[i+2]);hist[y]++}const total=c.width*c.height;let acc=0,lo=0,hi=255;for(let i=0;i<256;i++){acc+=hist[i];if(acc>=total*.03){lo=i;break}}acc=0;for(let i=255;i>=0;i--){acc+=hist[i];if(acc>=total*.04){hi=i;break}}if(hi-lo<60){lo=Math.max(0,lo-30);hi=Math.min(255,hi+30)}for(let i=0;i<p.length;i+=4){let y=.299*p[i]+.587*p[i+1]+.114*p[i+2];y=Math.max(0,Math.min(255,(y-lo)*255/Math.max(1,hi-lo)));if(strong)y=y<150?Math.max(0,y*.72):Math.min(255,185+(y-150)*1.4);else y=Math.pow(y/255,.9)*255;p[i]=p[i+1]=p[i+2]=Math.round(y)}ctx.putImageData(im,0,0);return c}
function ocrParsedQuality(p){let n=0;if(digits(p?.cnpj||'').length===14)n+=3;if(p?.date_time)n+=3;if(Number(p?.value)>0)n+=2;if(validFiscalVendor(p?.establishment))n+=2;if(p?.payment_method)n+=1;if(p?.card_last4)n+=1;return n}
function companyAddressFromBrasilApi(c){const street=[c?.descricao_tipo_de_logradouro,c?.logradouro].filter(Boolean).join(' '),first=[street,c?.numero&&String(c.numero)!=='S/N'?c.numero:null,c?.complemento].filter(Boolean).join(', '),second=[c?.bairro,c?.municipio,c?.uf].filter(Boolean).join(' - '),cep=digits(c?.cep||'');return[first,second,cep?`CEP ${cep.slice(0,5)}-${cep.slice(5)}`:''].filter(Boolean).join(' · ')}
async function lookupCompanyByCnpj(cnpj){const d=digits(cnpj);if(d.length!==14)return null;const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),4500);try{const r=await fetch(`https://brasilapi.com.br/api/cnpj/v1/${d}`,{signal:ctl.signal,headers:{accept:'application/json'}});if(!r.ok)return null;const c=await r.json();return{trade_name:String(c.nome_fantasia||'').trim(),legal_name:String(c.razao_social||'').trim(),address:companyAddressFromBrasilApi(c)}}catch(e){console.warn('CNPJ lookup',e);return null}finally{clearTimeout(tm)}}
'''
js=js.replace(anchor,helpers+anchor,1)

# Replace scanFiscal with preprocessing, conditional second pass, date cleanup and CNPJ confirmation.
pattern=r"async function scanFiscal\(file\)\{.*?\}\nfunction openCaptureMenu"
replacement=r'''async function scanFiscal(file){if(!file)return;$('scanStatus').textContent='Preparando imagem para leitura…';for(const id of ['eVendor','eVendorDoc','eAmount','eDate'])if($(id)&&!manualTouched.has(id))$(id).value='';let qr='',qrUsed=false,ocrUsed=false;try{if('BarcodeDetector'in window){const detector=new BarcodeDetector({formats:['qr_code']}),bmp=await createImageBitmap(file),codes=await detector.detect(bmp);qr=codes?.[0]?.rawValue||'';qrUsed=Boolean(qr)}}catch(e){console.warn('QR foto',e)}let text='',parsed={};try{const T=await loadTesseract(),img=await prepareOcrImage(file,false);const result=await T.recognize(img,'por',{logger:m=>{if(m.status==='recognizing text')$('scanStatus').textContent=`Lendo comprovante… ${Math.round((m.progress||0)*100)}%`;}},{tessedit_pageseg_mode:'6',preserve_interword_spaces:'1'});text=result?.data?.text||'';parsed=parseFiscalText(text,qr);if(!parsed.date_time)parsed.date_time=findOcrDateTime(text);let quality=ocrParsedQuality(parsed);if(quality<7){$('scanStatus').textContent='Refinando leitura do comprovante…';const img2=await prepareOcrImage(file,true),result2=await T.recognize(img2,'por',{}, {tessedit_pageseg_mode:'11',preserve_interword_spaces:'1'}),text2=result2?.data?.text||'';const merged=[text,text2].filter(Boolean).join('\n');const p2=parseFiscalText(merged,qr);if(!p2.date_time)p2.date_time=findOcrDateTime(merged);if(ocrParsedQuality(p2)>=quality){text=merged;parsed=p2;quality=ocrParsedQuality(p2)}}ocrUsed=Boolean(text.trim())}catch(e){console.warn('OCR',e);parsed=parseFiscalText('',qr)}if(parsed.cnpj){$('scanStatus').textContent='Confirmando estabelecimento pelo CNPJ…';const co=await lookupCompanyByCnpj(parsed.cnpj);if(co){parsed.trade_name=co.trade_name||parsed.trade_name||'';parsed.legal_name=co.legal_name||parsed.legal_name||'';parsed.establishment=co.trade_name||co.legal_name||parsed.establishment;if(!parsed.address&&co.address)parsed.address=co.address}}if(!validFiscalVendor(parsed.establishment)){parsed.establishment='';if(!validFiscalVendor(parsed.trade_name)&&!validFiscalVendor(parsed.legal_name)){parsed.trade_name='';parsed.legal_name=''}}parsed.qr_used=qrUsed;parsed.ocr_used=ocrUsed;parsed.ocr_text=text;parsed.consumer_document=localConsumerFromText(text,parsed.cnpj);parsed.items=localItemsFromText(text);parsed.category_hint=inferredCategory({...parsed,ocr_text:text});fillFiscal(parsed,true);const missing=[];if(!validFiscalVendor([parsed.trade_name,parsed.legal_name,parsed.establishment].find(validFiscalVendor)||''))missing.push('estabelecimento');if(!parsed.date_time)missing.push('data');$('scanStatus').textContent=(qrUsed||ocrUsed)?(missing.length?`Leitura concluída, mas não identifiquei com segurança: ${missing.join(' e ')}. Confira os campos.`:'Leitura concluída. Confira os dados antes de salvar.'):'Não consegui ler automaticamente. Você ainda pode anexar o comprovante e preencher os dados manualmente.'}
function openCaptureMenu'''
js,n=re.subn(pattern,lambda m:replacement,js,count=1,flags=re.S)
if n!=1: raise SystemExit(f'scanFiscal replacement count={n}')

html=re.sub(r'\.\/despesas-reembolsos-v2\.js\?v=\d+', './despesas-reembolsos-v2.js?v=20', html)
js_path.write_text(js,encoding='utf-8')
html_path.write_text(html,encoding='utf-8')
print('OCR image preprocessing, fallback pass, CNPJ confirmation and safe date handling applied')
